### ISSUE TITLE
Animated webps always play at 12 fps

### ISSUE THREAD

**Issue by Cguy7777** [hydrusnetwork/hydrus#1694]
### Hydrus version

v614

### Qt major version

Qt 6

### Operating system

Linux (specify distro and version in comments)

### Install method

Running from source

### Install and OS comments

Pop!_OS 22.04 LTS

### Bug description and reproduction

1. Play an animated webp (that isn't encoded at 12 fps).

Expected result:
The animation plays with the frame delays specified in the file.

Actual result:
The animation always plays at 12 fps.

### Log output

```text

```

**Comment by hydrusnetwork** [comment]
Thank you for this report. I believe the problem here is that our image library, Pillow, _can_ recognise when a webp has multiple frames, and it can now render those frames for us, but it cannot (yet) parse and provide duration data. Our fallback when we cannot find duration for an animation is 12fps.

I think we are basically waiting for a new version of Pillow or FFMPEG or whatever to be able to provide us with frame times and then I'll be able to fix this. There's an off chance I write my own frame timing parser, as I did for APNG, but I'm afraid I am generally not well suited to this sort of work, and I haven't looked into it yet, and I don't know how complicated webp is.

I will make a job to recheck the current status of all this, but looking at the code, if Pillow updates one day and gets it, then suddenly it'll all just work on our end on a newly imported webp (or one one that you right-click and say `manage->maintenance->regen file metadata`).

I have some animated webps with different durations, so I am ready to test this when it happens.

**Comment by hydrusnetwork** [comment]
I believe I have fixed this for v620. (I had some time today and wrote a webp chunk parser--it wasn't tricky in the end) All animated webps will be scheduled for a rescan on update and will get corrected durations. They should render in the native viewer with variable frame-rate OK!

Let me know if you run into any more trouble here!

**Comment by Cguy7777** [comment]
Thank you for working on this, most animated webps are playing correctly now!

However, I'm still seeing issues with a few of them, maybe because they have variable frame delays? Here's an example of one that doesn't playback properly: https://github.com/VintageAppMaker/WebpTest/blob/master/app/src/main/assets/test.webp
