### ISSUE TITLE
Boot Error: ClientGuiStyle.py  -  Style "windowsvista" cound not be generated/applied.

### ISSUE THREAD

**Issue by Albireo6972** [hydrusnetwork/hydrus#1739]
### Hydrus version

624

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Extract

### Bug description and reproduction

Updated to v624
Starting Hydrus shows boot error

![Image](https://github.com/user-attachments/assets/996d2925-6576-4c34-b15b-bb6836db1b64)

### Log output

```text

```

**Comment by Albireo6972** [comment]
Fixed, should have tried to do a fresh install before posting. That is one me, working now.

**Comment by trollusk** [comment]
This still happens, it seems that v624 and v625 cannot work with v623 or older databases - they exit with this error message.
