### ISSUE TITLE
Animated gifs leave gunk behind in the image viewer, and zooming causes artifacts to appear

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#52]
This also partially affects the thumbnail view.

Test with: https://d.maxfile.ro/ouulnzploq.gif

Screenshots of the issue:
--------------------------------

Thumbnail viewer:
![Screenshot](https://d.maxfile.ro/rbkgjandev.png)
Image viewer before zoom:
![Screenshot](https://d.maxfile.ro/hbozqbukxe.png)
Image viewer after zoom:
![Screenshot](https://d.maxfile.ro/qagvrupiix.png)

**Comment by hydrusnetwork** [comment]
Thank you, I will look into this.

**Comment by ScoreUnder** [comment]
There is another strange behaviour in the built-in GIF viewer and previewer.

This GIF:
![Image](https://d.maxfile.ro/ffalznnkyh.gif)
Displays like this in Hydrus:
![Hydrus preview of the above](https://d.maxfile.ro/kscawjhtci.png)

For some reason the white isn't getting drawn.

**Comment by hydrusnetwork** [comment]
This new crab one is interesting. Depending on whether I render with PIL or OpenCV, I get this:

Win PIL Rozen Bad Crab Bad
Linux PIL Rozen Bad Crab OK
OS X PIL Rozen Bad Crab Bad

Win OpenCV 2 Rozen OK (I think), Don't know crab
Linux OpenCV 2 Complete shit after the first frame, but no errors
OS X OpenCV 2 Can't remember, probably same as Linux

Win OpenCV 3 Rozen OK Crab OK
Linux OpenCV 3 Don't know
OS X OpenCV 3 Rozen Bad Crab OK

OpenCV 3.0.0 seems to be an improvement. At the moment, Linux and OS X default to PIL, while Windows tries to do CV and if that throws an error it falls back to PIL. I am not sure why Linux's PIL renders the crab ok for me, especially as it doesn't for you. I have set v180 to try CV if it is version 3.0.0, no matter the platform.

I use Ubuntu, which doesn't yet have an apt-get call to install OpenCV as far as I know, and I don't want to mess around with building it myself, so for now my Linux executable will have OpenCV 2, but if you run from source and have OpenCV 3.0.0, you should see an improvement next week.

I have neglected these github issues, but I am trying to get my schedule back on track. I also get the transparency crap on resize for that Rozen image, so I'll make sure to look at it this week.

**Comment by hydrusnetwork** [comment]
Zoom gunk is fixed, btw. It was a bmp reinit-clearing thing that wasn't happening automatically in Linux. I will update my Linux build to OpenCV 3.0.0 when that is sensible for Ubuntu, but anyone running from source who does have 3.0.0 should already see some improvement.

**Comment by ScoreUnder** [comment]
I've tested this on OpenCV 3.0.0 and it works on my machine. OpenCV 2.x is still buggy as usual, but I guess upgrading won't hurt.
